name: Deploy to Vultr

# 언제 실행할지 설정
on:
  push:
    branches: [ main ]  # main 브랜치에 push될 때

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3
    
    # 2. Node.js 설정
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    # 3. 의존성 설치
    - name: Install dependencies
      run: npm ci
    
    # 4. 프로젝트 빌드
    - name: Build project
      run: npm run build
    
    # 5. 서버에 연결 설정
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_actions
        chmod 600 ~/.ssh/github_actions
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
    
    # 6. 빌드 파일 서버로 전송
    - name: Deploy to server
      run: |
        rsync -avz --delete \
          -e "ssh -i ~/.ssh/github_actions" \
          ./build/ \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.WORK_DIR }}/build/
    
    # 7. 서버에서 권한 설정
    - name: Set permissions
      run: |
        ssh -i ~/.ssh/github_actions \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "chown -R www-data:www-data ${{ secrets.WORK_DIR }}"